[package]
name = "tls-api-openssl"
version = "0.1.9"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API implementation over openssl crate"
license = "MIT/Apache-2.0"
repository = "https://github.com/stepancheg/rust-tls-api/"
keywords = ["tls"]
build = "build.rs"

[badges]
travis-ci = { repository = "https://github.com/stepancheg/rust-tls-api/", branch = "master" }

[dependencies]
# To implement OpenSSL version check in build.rs
openssl-sys = { git = "https://github.com/valarauca/rust-openssl"  }
openssl     = { git = "https://github.com/valarauca/rust-openssl" , features = ["v102", "v110"]}
tls-api     = { version = "0.1.9", path = "../api" }

[dev-dependencies]
tls-api-test = { version = "0.1.9", path = "../api-test" }
